config-version: 2

name: dbt_task_analytics
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 70471823480395 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# vars:
#   "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  dbt_task_analytics:
    +schema: raw
    # jaffle-data:
    #   +enabled: "{{ var('load_source_data', false) }}"

models:
  dbt_task_analytics:
    staging:
      +schema: dev
      +materialized: view
    marts:
      +schema: dev
      +materialized: table
